
server:
  port: 8666

spring:
  datasource:
    driverClassName: org.h2.Driver
    #    url: jdbc:h2:mem:test  # 内存
    url: jdbc:h2:./h2dbFile/test  # 磁盘
    #url:jdbc:h2:tcp//localhost/?/test # 网络
    username: root
    password: 123123
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      data-locations: classpath:db/data.sql
      platform: h2
      schema-locations: classpath:db/table.sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging: ###配置sql打印日志
  level:
    com.example.demo2.dao: DEBUG
    org.springframework.web: DEBUG
    java.sql: DEBUG
    org.mybatis.spring: DEBUG
thread:
  pool:
    core-pool-size: 5
    maximum-pool-size: 10
    keep-alive-time: 60
    work-queue-size: 10000
